/geometry/source geom/NICE/CsI2in10cm.CF6in.tg
/output/file AmBe.root
/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree
/geometry/test/run

/vis/open HepRepFile
#/vis/drawVolume
/vis/scene/add/axes 0 0 0 15 cm

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 50
/vis/viewer/refresh
/vis/viewer/flush

/control/execute macro/src/AmBe.mac
/gps/pos/centre 0 0 -22.5 cm

/tracking/verbose 2

/run/beamOn 50
