/geometry/source geom/NICE/CsI2in10cm.CF6in.tg

/physics_lists/enable RadioactiveDecay
/physics_lists/enable HadronInelastic
/physics_lists/enable HadronElastic

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree
/geometry/test/run

/process/list

# AmBe neutron spectrum
/control/execute macro/src/AmBe.mac
/gps/pos/centre 0 0 -22.5 cm

/random/setSeeds 2412 79628

/output/file AmBe.root

/run/statusReport 100000
/run/beamOn 500000
