/geometry/source CsI3inWLS.tg

/physics_lists/enable Optical
/process/optical/processActivation Scintillation
/process/optical/processActivation OpBoundary
/process/optical/processActivation OpAbsorption false
/process/optical/processActivation OpRayleigh false
/process/optical/processActivation OpMieHG false
/process/optical/processActivation Cerenkov false
/process/optical/processActivation OpWLS false

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree
/geometry/test/run

/process/list
/process/setVerbose 10 OpBoundary

/vis/open OGLIQt
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories

/gps/particle gamma
/gps/energy 1 keV
/gps/position 0 0 0 cm

/tracking/verbose 2
/run/beamOn 1
