/control/verbose
/process/em/verbose 0
/process/had/verbose 0

/geometry/source detector.tg

/physics_lists/factory/addOptical

/run/initialize

/gps/particle gamma
/gps/energy 1 keV
/gps/ang/type iso


/control/ifInteractive ogl.mac

/tracking/verbose 2
/run/beamOn
/tracking/verbose 0

/control/doifBatch /vis/disable
/control/doifBatch /analysis/setFileName scintillation.root
/run/verbose 2
/control/doifBatch /run/beamOn 5000

