/geometry/source ../gears.tg

/run/initialize

/geometry/test/run
/vis/geometry/list

/control/shell dawn -c
/control/shell rm -f *.prim g4_????.eps gears.png

/vis/open DAWNFILE
/vis/viewer/set/background white ! ! 0
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 15 20
/vis/viewer/set/projection perspective
/vis/viewer/set/lineSegmentsPerCircle 60
/vis/geometry/set/lineWidth ! ! 0
/vis/drawVolume
/vis/viewer/flush

/control/shell convert g4_????.eps -trim +repage gears.png
