#!/bin/bash

# get the latest g4_??.wrl
for each in `ls *.wrl 2>&1`; do latest=$each; done
if [ "$latest" = directory ]; then echo "no g4_??.wrl file found"; exit; fi

# get VRML to X3D converter
JAR="VrmlMerge-0.5beta.jar"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
if [ ! -f $DIR/$JAR ]; then
  curl -L https://www.dropbox.com/s/fjc2q7lafnotk4i/$JAR?dl=1 -o $DIR/$JAR
fi

# convert VRML to X3D
X3D=${latest/wrl/x3d}
if [ ! -f $X3D ] || [ $latest -nt $X3D ]; then
    java -jar $DIR/$JAR -convert $latest $X3D
fi

# tune transparency in $X3D
sed -i.bak 's/"0.7"/"0.1"/g' $X3D
rm *.bak

# embed g4_??.x3d in g4_??.html
cat << END > ${latest/wrl/html}
<html> 
<head> 
<title>$X3D</title>
<script type='text/javascript' src='http://www.x3dom.org/download/x3dom.js'> </script>
<link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/x3dom.css'></link>
</head> 
<body>
Rotate:
<img width="50px" src="https://doc.x3dom.org/tutorials/animationInteraction/navigation/img/Mouse_Left.png"/>
Zoom:
<img width="50px" src="https://doc.x3dom.org/tutorials/animationInteraction/navigation/img/Mouse_Right.png"/>
Zoom:
<img width="50px" src="https://doc.x3dom.org/tutorials/animationInteraction/navigation/img/Mouse_Wheel_Scroll.png"/>
Pan:
<img width="50px" src="https://doc.x3dom.org/tutorials/animationInteraction/navigation/img/Mouse_Wheel_Press.png"/>
More:
<a href="https://doc.x3dom.org/tutorials/animationInteraction/navigation/">X3DOM Documentation</a>
<x3d> 
<scene>
<inline url="$X3D"></inline> 
</scene> 
</x3d> 
</body>
</html>
END

# server the current directory
echo click http://127.0.0.1:8888/${latest/wrl/html} to view $X3D
python3 -m http.server 8888 -b 127.0.0.1
