#!/bin/bash

# get the latest g4_??.wrl
for each in `ls *.wrl 2>&1`; do latest=$each; done
if [ "$latest" = directory ]; then echo "no g4_??.wrl file found"; exit; fi

# convert VRML to X3D
JAR="VrmlMerge-0.5beta.jar"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
X3D=${latest/wrl/x3d}
if [ ! -f $X3D ] || [ $latest -nt $X3D ]; then
    java -jar $DIR/$JAR -convert $latest $X3D
fi

# tune transparency in $X3D
sed -i.bak 's/"0.7"/"0.1"/g' $X3D
rm *.bak

# embed g4_??.x3d in g4_??.html
sed "s/gears/$latest/" gearsX3D.html > ${latest/wrl/html}

# server the current directory if python3 exists
p3=`command -v python3`
if [ X"$p3" = X ]; then
  echo "${latest/wrl/html} is created"
else
  echo ${latest/wrl/html} with $X3D embedded is served at
  $p3 -m http.server 8888 -b 127.0.0.1
fi

