/vis/open OGL
/vis/drawVolume

/vis/viewer/zoomTo 2
/vis/viewer/set/auxiliaryEdge
/vis/viewer/set/lineSegmentsPerCircle 6
/vis/viewer/set/viewpointVector 0.75 0.66 0.12
/vis/viewer/set/background white

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 5
/vis/modeling/trajectories/drawByParticleID-0/setDefaultRGBA 0 0.78 0.55 1

/vis/scene/add/axes
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/run/beamOn 10

/vis/ogl/export scattering.png

