/geometry/source tracker.tg
#/geometry/source LINEAR_X.tg
/field/SetB 0 0 1e-1 tesla

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree

/vis/geometry/list

/control/shell dawn -c
/control/shell rm -f *.prim *.eps tracker.png

/vis/open DAWNFILE
/vis/drawVolume

/vis/scene/add/magneticField
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
/vis/scene/add/text 1.5 9.5 0 cm 20 0 0 electron
/vis/scene/add/text 8 0.3 0 cm 20 0 0 neutron
/vis/scene/add/text 8 -2 0 cm 20 0 0 alpha
/vis/scene/add/text 2 -10.5 0 cm 20 0 0 positon

/vis/viewer/set/background white ! ! 0

/gps/source/multiplevertex true

/gps/source/intensity 0.25
/gps/particle alpha
/gps/energy 5 MeV
/gps/pos/centre -9 -0.1 0 cm
/gps/direction 1 0 0

/gps/source/add 0.25 
/gps/particle e-
/gps/energy 5 MeV
/gps/pos/centre -9 0.1 0 cm
/gps/direction 1 0 0

/gps/source/add 0.25 
/gps/particle e+
/gps/energy 5 MeV
/gps/pos/centre -9 0.1 0 cm
/gps/direction 1 0 0

/gps/source/add 0.25 
/gps/particle neutron
/gps/energy 5 MeV
/gps/pos/centre -9 0.1 0 cm
/gps/direction 1 0 0

/run/beamOn 1

/control/shell convert g4_*.eps -trim +repage tracker.png
