/control/verbose
/process/em/verbose 0
/process/had/verbose 0

/geometry/source PMTwindow.tg

/physics_lists/factory/addOptical
#/process/optical/processActivation Cerenkov false

/run/initialize

/geometry/test/run

/gps/particle e-
/gps/energy 511 keV
/gps/position 0 0 1.01 mm

/control/ifInteractive ogl.mac

/tracking/verbose 2
/run/beamOn 2
/tracking/verbose 0

/control/doifBatch /analysis/setFileName Cherenkov.root
/control/doifBatch /run/beamOn 5000

