/geometry/textInput/file geo/Rutherford/magnet.tg
/field/setM 0 0 1e-3 tesla

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree
/geometry/test/run

/vis/open DAWNFILE
/vis/drawVolume
/vis/scene/add/trajectories

/gps/source/multiplevertex true

/gps/source/intensity 0.5
/gps/particle alpha
/gps/energy 5 MeV
/gps/pos/centre -9 -0.1 0 cm
/gps/direction 1 0 0

/gps/source/add 0.5 
/gps/particle e-
/gps/energy 50 keV
/gps/pos/centre -9 0.1 0 cm
/gps/direction 1 0 0

/run/beamOn 1
