/geometry/textInput/file geo/Rutherford/foil.tg
/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree
/geometry/test/run

/vis/open DAWNFILE
/vis/viewer/set/background ! ! ! 0
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/zoom 2
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 50

/gps/particle alpha
/gps/energy 5 MeV
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/radius 5 cm
/gps/pos/centre 0 0 1 cm

/run/beamOn 50
