/control/verbose
/process/em/verbose 0
/process/had/verbose 0

/geometry/source CsI2PMT.tg

/physics_lists/factory/addOptical

/run/initialize

/geometry/test/run

/gps/particle opticalphoton
/gps/energy 3.5 eV
/gps/polarization 0 1 0
/gps/position 0 0 -2 cm

/tracking/verbose 2
/run/beamOn 2
/tracking/verbose 0

/control/ifInteractive ogl.mac

/control/doifBatch /analysis/setFileName ideal.root
/control/doifBatch /run/beamOn 5000

